### ISSUE TITLE
zenpath bug?

### ISSUE THREAD

**Issue by cbhurley** [great-northern-diver/zenplots#10]
w <- rpois(4,10)
zpairs <- cbind(1:4, c(5,6,6,6))
zenpath(w, pairs=zpairs, method="greedy.weighted")

**Comment by rwoldford** [comment]
Hi Catherine
I think the problem is that the graph you gave by zpairs is not connected.

> zpairs
     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    6
[4,]    4    6

Nodes 1 and 5 are not connected to the star graph formed by 2,3,4, and 6.

Zenpath needs a connected graph to work with.  We should probably update the documentation to say that.   And maybe check for it.

I guess we could do it and return a list of Eulerians.   This would require us to identify the connectedness up front.   I am pretty sure that is a bit of work (depth-first search?) to do up front as a check.
As it now stands, the user would have to do so and call zenpath on each component of the graph.

Do you think I should write a function is_connected() to test?
Are you imagining using graphs that you do not know up front are connected?

**Comment by cbhurley** [comment]
Yes, I reckoned that was the problem.
I could use the strictly weighted version to get a path, or code up something myself. But, when it works the weighted path is better (shorter).

The application is something like this: suppose you have a scatter plot matrix and a measure of interestingness. You find the subset of plots that are interesting, in the top 10% say, and feed those with a path to zen plots. So you would have no idea if the graph of pairs was connected or not.

Though, in the variant I’ve coded up, the plots are not scatter plots, instead bivariate partial dependence plots from a model fit, eg random forest. Works a treat!
Because you want all the plots to have the same z limits, I precalculated the plots, and them fed them in to the plot2d. I had done a ggpairs version as well, but the zen plots is one way of handling the large p problem.


Had a student working on this, and he was stuck. Don’t think he could get his head around zen plots and eulerians. I tried to explain it to him, but it is not easy on a zoom call.

Hope you are doing well. We had a semi lockdown for last month (to get ready for Christmas), now things are opening up somewhat so reckon the numbers will take off again in the new year, or even before.
I’m working from home all the time. All lectures given live and recorded on teams. Students are not complaining, though in person lectures generally have a lot more questions and interaction.

Cheers

Catherine

—————————————————————————————-
Dr. Catherine Hurley
Maynooth University Department of Mathematics and Statistics
________________________________
